"""Reference implementations to compare a candidate against.

Two kinds:

  TorchReference   an oracle expressed in PyTorch. Always available, runs on CPU,
                   and is what you use to develop the harness itself.
  NativeReference  compiles the ORIGINAL .cu with nvcc (or the hipified source
                   with hipcc) and runs it on a real device. This is the only
                   reference that proves anything about the kernel you were
                   actually given, so it is the one that matters.

Availability is detected, never assumed. A missing toolchain yields an
unavailable reference with a reason, not an exception at import time.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

import torch

# Re-exported: this module was its home, and hipbridge.verify still offers it.
from hipbridge.analysis import wavefront_for


@dataclass(frozen=True)
class Availability:
    ok: bool
    reason: str = ""

    def __bool__(self) -> bool:
        return self.ok


class Reference:
    """Base protocol: given input tensors, return the expected output."""

    name = "reference"

    def availability(self) -> Availability:  # pragma: no cover - overridden
        raise NotImplementedError

    def __call__(self, *inputs: torch.Tensor) -> torch.Tensor:  # pragma: no cover
        raise NotImplementedError


@dataclass
class TorchReference(Reference):
    """An oracle written in PyTorch."""

    fn: Callable[..., torch.Tensor]
    name: str = "torch"

    def availability(self) -> Availability:
        return Availability(True)

    def __call__(self, *inputs: torch.Tensor) -> torch.Tensor:
        return self.fn(*inputs)


@dataclass(frozen=True)
class LaunchSpec:
    """How to launch the kernel under test.

    grid and block are callables of the input shapes so the driver can size the
    launch per case rather than hardcoding one shape.
    """

    kernel: str
    grid: Callable[[Sequence[tuple[int, ...]]], tuple[int, int, int]]
    block: tuple[int, int, int] = (256, 1, 1)
    scalar_args: Callable[[Sequence[tuple[int, ...]]], list[int]] = lambda shapes: []
    n_outputs: int = 1
    out_shape: Callable[[Sequence[tuple[int, ...]]], tuple[int, ...]] | None = None


_DRIVER = r"""
// Generated by hipbridge.verify. Reads inputs from binary files, launches the
// kernel once, writes outputs back. Deliberately dumb: no timing, no streams.
#include <cstdio>
#include <cstdlib>
#include <vector>
%(header)s
%(scalar_header)s

// The element type this run uses. Kernels written against HB_SCALAR compile
// unchanged for float, half and bfloat16; those written against float still
// compile, and are simply float-only.
typedef %(scalar)s SCALAR;
#define HB_SCALAR SCALAR

%(kernel_source)s

// Raw bytes in, raw bytes out. The host never does arithmetic on the element
// type, so half and bfloat16 need no host-side conversion and the file layout
// is exactly what torch wrote.
static std::vector<SCALAR> read_bin(const char* path, size_t n) {
    std::vector<SCALAR> h(n);
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %%s\n", path); exit(2); }
    if (fread(h.data(), sizeof(SCALAR), n, f) != n) { fprintf(stderr, "short read\n"); exit(3); }
    fclose(f);
    return h;
}

static void write_bin(const char* path, const std::vector<SCALAR>& h) {
    FILE* f = fopen(path, "wb");
    if (!f) { fprintf(stderr, "cannot open %%s\n", path); exit(4); }
    fwrite(h.data(), sizeof(SCALAR), h.size(), f);
    fclose(f);
}

int main(int argc, char** argv) {
    // argv: prog n_in (path size)*n_in out_path out_size gx gy gz bx by bz scalars...
    int argi = 1;
    int n_in = atoi(argv[argi++]);
    std::vector<SCALAR*> d_in(n_in);
    for (int i = 0; i < n_in; ++i) {
        const char* path = argv[argi++];
        size_t n = (size_t)atoll(argv[argi++]);
        auto h = read_bin(path, n);
        %(malloc)s(&d_in[i], n * sizeof(SCALAR));
        %(memcpy)s(d_in[i], h.data(), n * sizeof(SCALAR), %(h2d)s);
    }
    const char* out_path = argv[argi++];
    size_t out_n = (size_t)atoll(argv[argi++]);
    SCALAR* d_out = nullptr;
    %(malloc)s(&d_out, out_n * sizeof(SCALAR));

    // Fill the output with a sentinel so a kernel that never stores is caught.
    std::vector<SCALAR> sentinel(out_n, %(from_float)s(-12345.0f));
    %(memcpy)s(d_out, sentinel.data(), out_n * sizeof(SCALAR), %(h2d)s);

    int gx = atoi(argv[argi++]), gy = atoi(argv[argi++]), gz = atoi(argv[argi++]);
    int bx = atoi(argv[argi++]), by = atoi(argv[argi++]), bz = atoi(argv[argi++]);
    std::vector<int> scalars;
    for (; argi < argc; ++argi) scalars.push_back(atoi(argv[argi]));

    %(launch)s

    %(sync)s();
    auto err = %(last_error)s();
    if (err != %(success)s) {
        fprintf(stderr, "kernel error: %%s\n", %(error_string)s(err));
        return 5;
    }

    std::vector<SCALAR> h_out(out_n);
    %(memcpy)s(h_out.data(), d_out, out_n * sizeof(SCALAR), %(d2h)s);
    write_bin(out_path, h_out);

    // Optional device-side timing, enabled by HIPBRIDGE_REPS so it cannot
    // collide with the scalar arguments, which consume the rest of argv.
    // Events time the kernel on device and exclude the file I/O and host
    // copies above, which would otherwise dominate and make every kernel look
    // the same speed.
    const char* reps_env = getenv("HIPBRIDGE_REPS");
    int reps = reps_env ? atoi(reps_env) : 0;
    if (reps > 0) {
        int warmup = reps / 10 > 3 ? reps / 10 : 3;
        for (int i = 0; i < warmup; ++i) { %(launch)s }
        %(sync)s();

        %(event_t)s beg, end;
        %(event_create)s(&beg); %(event_create)s(&end);
        %(event_record)s(beg, 0);
        for (int i = 0; i < reps; ++i) { %(launch)s }
        %(event_record)s(end, 0);
        %(event_sync)s(end);
        float total_ms = 0.0f;
        %(event_elapsed)s(&total_ms, beg, end);
        printf("KERNEL_MS %%.9f\n", total_ms / (float)reps);
    }
    return 0;
}
"""

_CUDA_TOKENS = {
    "header": "#include <cuda_runtime.h>",
    "malloc": "cudaMalloc",
    "memcpy": "cudaMemcpy",
    "h2d": "cudaMemcpyHostToDevice",
    "d2h": "cudaMemcpyDeviceToHost",
    "sync": "cudaDeviceSynchronize",
    "last_error": "cudaGetLastError",
    "success": "cudaSuccess",
    "error_string": "cudaGetErrorString",
    "event_t": "cudaEvent_t",
    "event_create": "cudaEventCreate",
    "event_record": "cudaEventRecord",
    "event_sync": "cudaEventSynchronize",
    "event_elapsed": "cudaEventElapsedTime",
}

_HIP_TOKENS = {
    "header": "#include <hip/hip_runtime.h>",
    "malloc": "hipMalloc",
    "memcpy": "hipMemcpy",
    "h2d": "hipMemcpyHostToDevice",
    "d2h": "hipMemcpyDeviceToHost",
    "sync": "hipDeviceSynchronize",
    "last_error": "hipGetLastError",
    "success": "hipSuccess",
    "error_string": "hipGetErrorString",
    "event_t": "hipEvent_t",
    "event_create": "hipEventCreate",
    "event_record": "hipEventRecord",
    "event_sync": "hipEventSynchronize",
    "event_elapsed": "hipEventElapsedTime",
}

SENTINEL = -12345.0

# Element types the generated driver can carry, and what each needs to say so.
# Half precision is what inference runs in, so a reference that could only
# compile float32 could only prove a claim about a precision nobody deploys.
#
# The host never does arithmetic on these: buffers are read and written as raw
# bytes, so the only host-side conversion is the sentinel that catches a kernel
# which never stores.
_SCALARS = {
    "float32": {
        "hipcc": ("float", "", "(float)"),
        "nvcc": ("float", "", "(float)"),
    },
    "float16": {
        "hipcc": ("__half", "#include <hip/hip_fp16.h>", "__float2half"),
        "nvcc": ("__half", "#include <cuda_fp16.h>", "__float2half"),
    },
    "bfloat16": {
        "hipcc": ("__hip_bfloat16", "#include <hip/hip_bf16.h>", "__float2bfloat16"),
        "nvcc": ("__nv_bfloat16", "#include <cuda_bf16.h>", "__float2bfloat16"),
    },
}


def scalar_tokens(dtype_name: str, toolchain: str) -> dict[str, str]:
    """Driver tokens for one element type, or a clear failure."""
    per_type = _SCALARS.get(dtype_name)
    if per_type is None:
        raise TypeError(
            f"no driver support for {dtype_name}; known types are {', '.join(sorted(_SCALARS))}"
        )
    scalar, header, from_float = per_type[toolchain]
    return {"scalar": scalar, "scalar_header": header, "from_float": from_float}


def _to_bytes(t: torch.Tensor) -> bytes:
    """Tensor to the exact bytes the driver will read.

    numpy has no bfloat16, so that type travels through an int16 view: the bits
    are the point, and reinterpreting them costs nothing and loses nothing.
    """

    flat = t.detach().cpu().contiguous().reshape(-1)
    if flat.dtype is torch.bfloat16:
        return flat.view(torch.int16).numpy().tobytes()
    return flat.numpy().tobytes()


def _from_bytes(raw: bytes, dtype: torch.dtype) -> torch.Tensor:
    """The driver's output bytes back into a tensor of the same type."""
    import numpy as np  # noqa: PLC0415

    if dtype is torch.bfloat16:
        arr = np.frombuffer(raw, dtype=np.int16).copy()
        return torch.from_numpy(arr).view(torch.bfloat16)
    np_dtype = {torch.float32: np.float32, torch.float16: np.float16}.get(dtype)
    if np_dtype is None:
        raise TypeError(f"no host mapping for {dtype}")
    return torch.from_numpy(np.frombuffer(raw, dtype=np_dtype).copy())


def _device_present(toolchain: str) -> bool:
    """Is a real device visible to the vendor runtime?

    Deliberately NOT torch.cuda.is_available(). The CPU-only torch wheel is the
    default on Windows and on any `pip install torch` without a vendor index, so
    torch reports no CUDA on machines that plainly have a working GPU and
    toolkit. NativeReference compiles and runs its own binary and never touches
    torch's runtime, so gating on torch's build flavour is simply the wrong
    question.
    """
    probe = "nvidia-smi" if toolchain == "nvcc" else "rocm-smi"
    if shutil.which(probe):
        try:
            r = subprocess.run(
                [probe, "-L"] if probe == "nvidia-smi" else [probe],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if r.returncode == 0 and r.stdout.strip():
                return True
        except (OSError, subprocess.SubprocessError):
            pass
    # Fall back to torch only as a secondary signal, never as the gate.
    return bool(toolchain == "nvcc" and torch.cuda.is_available())


def _host_compiler_missing(toolchain: str) -> str:
    """nvcc drives a host C++ compiler and cannot build without one.

    On Windows that is MSVC cl.exe, which is a separate install from the CUDA
    toolkit and from Visual Studio itself. Missing it produces
    `nvcc fatal: Cannot find compiler 'cl.exe' in PATH` at build time, so it is
    checked here instead: an availability probe that reports ok and then fails
    on the next call is worse than useless.

    Returns a reason string when unusable, empty when fine.
    """
    if toolchain != "nvcc" or sys.platform != "win32":
        return ""
    if shutil.which("cl"):
        return ""
    return (
        "nvcc present but MSVC host compiler (cl.exe) not on PATH. "
        "Install the Visual Studio Build Tools C++ workload, then run from a "
        "Developer Command Prompt, or build under WSL2 where nvcc uses gcc."
    )


def hip_include_flags(root: str | None = None) -> list[str]:
    """Locate the HIP headers and return compiler flags pointing at them.

    Some ROCm images use a component-split layout (/opt/rocm/core-<ver>/...)
    where hipcc cannot find its own headers and fails with
    `fatal error: 'hip/hip_runtime.h' file not found`, despite the compiler and
    runtime being present and gfx detection working. Observed on an AMD
    Developer Cloud MI300X image with HIP 7.14.

    Returns [] when the headers are already reachable or cannot be found; the
    compiler's own error is clearer than a guess.
    """
    candidates: list[Path] = []
    if root:
        candidates.append(Path(root) / "include")
    env = os.environ.get("ROCM_PATH")
    if env:
        candidates.append(Path(env) / "include")
    candidates.append(Path("/opt/rocm/include"))
    candidates += sorted(Path("/opt").glob("rocm-*/include"))
    candidates += sorted(Path("/opt/rocm").glob("*/include")) if Path("/opt/rocm").is_dir() else []
    # libamdhip64-dev is Debian-packaged and lands in /usr/include, not under
    # /opt/rocm where a ROCm tarball install would put it. Searching only /opt
    # misses a perfectly good apt-installed header.
    candidates += [Path("/usr/include"), Path("/usr/local/include")]

    for inc in candidates:
        if (inc / "hip" / "hip_runtime.h").is_file():
            # Only the include path. Do NOT derive --rocm-path from where the
            # header lives: with libamdhip64-dev the headers are under /usr
            # while the toolchain is under /opt/rocm, and --rocm-path=/usr makes
            # hipcc look for /usr/lib/llvm/bin/clang++ instead of the compiler
            # it already resolves correctly by itself.
            return [f"-I{inc}"]
    return []


def wsl(distro: str = "Ubuntu") -> list[str]:
    """Command prefix that runs the toolchain inside a WSL2 distribution.

    A very common developer setup is Windows for editing and WSL2 for the GPU
    toolchain: nvcc there drives gcc instead of MSVC, and ROCm is Linux-only, so
    the AMD half of any such project lives in WSL regardless. This lets the
    harness run in Windows Python while compiling and executing on the Linux
    side, against the same physical device.
    """
    return ["wsl", "-d", distro, "--"]


def to_wsl_path(p: Path | str) -> str:
    r"""Translate C:\Users\x to /mnt/c/Users/x. Already-POSIX paths pass through."""
    s = str(p)
    if len(s) > 1 and s[1] == ":":
        return "/mnt/" + s[0].lower() + s[2:].replace("\\", "/")
    return s.replace("\\", "/")


@dataclass
class NativeReference(Reference):
    """Compile and run the original kernel source on a real device."""

    source: str
    launch: LaunchSpec
    toolchain: str = "nvcc"  # "nvcc" or "hipcc"
    extra_flags: list[str] = field(default_factory=list)
    name: str = "native"
    # Optional prefix placed before every toolchain and driver invocation, e.g.
    # wsl("Ubuntu"). When set, paths are translated and the MSVC host-compiler
    # check is skipped, since the host compiler is whatever lives on that side.
    command_prefix: list[str] = field(default_factory=list)
    _built: Path | None = field(default=None, init=False, repr=False)
    _dtype_name: str = field(default="float32", init=False, repr=False)
    _reps: int = field(default=0, init=False, repr=False)
    last_kernel_ms: float | None = field(default=None, init=False, repr=False)

    @property
    def _remote(self) -> bool:
        return bool(self.command_prefix)

    def _path(self, p: Path) -> str:
        return to_wsl_path(p) if self._remote else str(p)

    def _run(self, argv: list[str], **kw) -> subprocess.CompletedProcess:
        return subprocess.run([*self.command_prefix, *argv], **kw)

    def availability(self) -> Availability:
        if self._remote:
            where = " ".join(self.command_prefix)
            try:
                r = self._run(
                    [self.toolchain, "--version"], capture_output=True, text=True, timeout=120
                )
            except (OSError, subprocess.SubprocessError) as exc:
                return Availability(False, f"cannot reach {where}: {exc}")
            if r.returncode != 0:
                return Availability(False, f"{self.toolchain} not usable via {where}")
            probe = "nvidia-smi" if self.toolchain == "nvcc" else "rocm-smi"
            d = self._run([probe, "-L"], capture_output=True, text=True, timeout=120)
            if d.returncode != 0 or not d.stdout.strip():
                return Availability(False, f"no device visible via {where}")
            return Availability(True)

        exe = shutil.which(self.toolchain)
        if exe is None:
            return Availability(False, f"{self.toolchain} not on PATH")
        if not _device_present(self.toolchain):
            return Availability(False, f"{self.toolchain} present but no device visible")
        host = _host_compiler_missing(self.toolchain)
        if host:
            return Availability(False, host)
        return Availability(True)

    def _render_driver(self) -> str:
        tokens = dict(_CUDA_TOKENS if self.toolchain == "nvcc" else _HIP_TOKENS)
        tokens.update(scalar_tokens(self._dtype_name, self.toolchain))
        args = ", ".join(
            [f"d_in[{i}]" for i in range(64)][: self._n_inputs]
            + ["d_out"]
            + [f"scalars[{i}]" for i in range(self._n_scalars)]
        )
        if self.toolchain == "nvcc":
            call = f"{self.launch.kernel}<<<dim3(gx,gy,gz), dim3(bx,by,bz)>>>({args});"
        else:
            call = (
                f"hipLaunchKernelGGL({self.launch.kernel}, dim3(gx,gy,gz), "
                f"dim3(bx,by,bz), 0, 0, {args});"
            )
        tokens["launch"] = call
        tokens["kernel_source"] = self.source
        return _DRIVER % tokens

    def build(self, n_inputs: int, n_scalars: int, dtype_name: str = "float32") -> Path:
        self._n_inputs, self._n_scalars = n_inputs, n_scalars
        self._dtype_name = dtype_name
        avail = self.availability()
        if not avail:
            raise RuntimeError(f"cannot build: {avail.reason}")

        # When running through a prefix the temp dir must be visible on both
        # sides, so it is created on the Windows filesystem and referenced via
        # its translated path rather than living in the guest's own /tmp.
        tmp = Path(tempfile.mkdtemp(prefix="hipbridge_ref_"))
        ext = ".cu" if self.toolchain == "nvcc" else ".hip.cpp"
        src = tmp / f"driver{ext}"
        src.write_text(self._render_driver(), encoding="utf-8", newline="\n")
        # Name by the platform that will RUN it, not the one rendering it:
        # through a prefix the binary executes on the guest side.
        windows_target = os.name == "nt" and not self._remote
        exe = tmp / ("driver.exe" if windows_target else "driver")

        flags = list(self.extra_flags)
        if self.toolchain == "hipcc" and not self._remote:
            if not any(f.startswith(("-I", "--rocm-path")) for f in flags):
                flags += hip_include_flags()
        cmd = [self.toolchain, self._path(src), "-o", self._path(exe), "-O2", *flags]
        r = self._run(cmd, capture_output=True, text=True)

        # Observed on an MI300X image whose apt HIP headers (/usr/include/hip)
        # are a different ROCm version from the compiler (/opt/rocm/core-7.14):
        #   amd_warp_functions.h: use of undeclared identifier
        #   '__AMDGCN_WAVEFRONT_SIZE'
        # The macro is normally predefined by the compiler. Supplying the value
        # for the target arch is correct and lets the build proceed; matching
        # header and compiler versions is the real fix.
        #
        # Only a known width is supplied. With no --offload-arch this assumed
        # gfx942 and defined 64, which on an RDNA card (32 wide) builds cleanly
        # with the wrong value, so every number after it inherits the mistake.
        skew = ""
        if r.returncode != 0 and "__AMDGCN_WAVEFRONT_SIZE" in (r.stdout + r.stderr):
            arch = next(
                (f.split("=", 1)[1] for f in flags if f.startswith("--offload-arch=")),
                "",
            )
            width = wavefront_for(arch)
            if width is None:
                skew = (
                    "\nThe HIP headers do not match the compiler, and the wavefront width "
                    f"for {arch or 'an unnamed arch'} is not known, so it was not guessed. "
                    "Pass --arch, or install headers matching the compiler "
                    "(scripts/install-hip-headers.sh)."
                )
            else:
                retry = [*cmd, f"-D__AMDGCN_WAVEFRONT_SIZE={width}"]
                r = self._run(retry, capture_output=True, text=True)
                if r.returncode == 0:
                    cmd = retry

        if r.returncode != 0:
            # nvcc reports fatal driver errors (a missing host compiler, for one)
            # on stdout, not stderr. Reporting only stderr yields an empty
            # message for the most common Windows failure there is.
            detail = "\n".join(x for x in (r.stdout.strip(), r.stderr.strip()) if x)
            raise RuntimeError(
                f"{self.toolchain} failed (exit {r.returncode}):\n"
                f"{detail[-2000:] or '(no output)'}\n"
                f"command: {' '.join(cmd)}{skew}"
            )
        self._built = exe
        return exe

    def __call__(self, *inputs: torch.Tensor) -> torch.Tensor:
        # The generated driver reads and writes 4-byte floats and the example
        # kernels take `const float *`. Handing it half precision would
        # reinterpret two values as one and compare the result against a correct
        # answer, which is a failure report that says nothing true about the
        # kernel. Refuse with the reason instead.
        # One element type per run, taken from the inputs. A kernel handed a
        # half tensor and a float table would silently read one of them wrong.
        kinds = {str(t.dtype).removeprefix("torch.") for t in inputs}
        if len(kinds) != 1:
            raise TypeError(f"every input must share one dtype; got {sorted(kinds)}")
        dtype_name = kinds.pop()

        shapes = [tuple(t.shape) for t in inputs]
        scalars = self.launch.scalar_args(shapes)
        # Rebuild when the element type changes: the driver is compiled for one.
        if self._built is None or dtype_name != self._dtype_name:
            self.build(len(inputs), len(scalars), dtype_name)
        assert self._built is not None

        tmp = self._built.parent
        argv: list[str] = [self._path(self._built), str(len(inputs))]
        for i, t in enumerate(inputs):
            p = tmp / f"in{i}.bin"
            p.write_bytes(_to_bytes(t))
            argv += [self._path(p), str(t.numel())]

        out_shape = self.launch.out_shape(shapes) if self.launch.out_shape else shapes[0]
        out_n = 1
        for d in out_shape:
            out_n *= d
        out_path = tmp / "out.bin"
        argv += [self._path(out_path), str(out_n)]
        argv += [str(x) for x in self.launch.grid(shapes)]
        argv += [str(x) for x in self.launch.block]
        argv += [str(x) for x in scalars]

        env = dict(os.environ)
        if self._reps:
            if self._remote:
                # A command prefix crosses a process boundary that does not
                # carry the parent environment: `wsl -- cmd` starts a fresh
                # session, so an exported variable here is invisible there.
                # Passing it through env(1) travels with the command instead.
                argv = ["env", f"HIPBRIDGE_REPS={self._reps}", *argv]
            else:
                env["HIPBRIDGE_REPS"] = str(self._reps)
        r = self._run(argv, capture_output=True, text=True, env=env)
        if r.returncode != 0:
            detail = "\n".join(x for x in (r.stdout.strip(), r.stderr.strip()) if x)
            raise RuntimeError(f"reference run failed (exit {r.returncode}): {detail[-1000:]}")

        self.last_kernel_ms = None
        for line in r.stdout.splitlines():
            if line.startswith("KERNEL_MS "):
                self.last_kernel_ms = float(line.split()[1])

        return _from_bytes(out_path.read_bytes(), inputs[0].dtype).reshape(out_shape)


__all__ = [
    "SENTINEL",
    "Availability",
    "LaunchSpec",
    "NativeReference",
    "Reference",
    "TorchReference",
    "hip_include_flags",
    "to_wsl_path",
    "wavefront_for",
    "wsl",
]
