"""Reference implementations to compare a candidate against.

Two kinds:

  TorchReference   an oracle expressed in PyTorch. Always available, runs on CPU,
                   and is what you use to develop the harness itself.
  NativeReference  compiles the ORIGINAL .cu with nvcc (or the hipified source
                   with hipcc) and runs it on a real device. This is the only
                   reference that proves anything about the kernel you were
                   actually given, so it is the one that matters.

Availability is detected, never assumed. A missing toolchain yields an
unavailable reference with a reason, not an exception at import time.
"""

from __future__ import annotations

import shutil
import struct
import subprocess
import tempfile
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

import torch


@dataclass(frozen=True)
class Availability:
    ok: bool
    reason: str = ""

    def __bool__(self) -> bool:
        return self.ok


class Reference:
    """Base protocol: given input tensors, return the expected output."""

    name = "reference"

    def availability(self) -> Availability:  # pragma: no cover - overridden
        raise NotImplementedError

    def __call__(self, *inputs: torch.Tensor) -> torch.Tensor:  # pragma: no cover
        raise NotImplementedError


@dataclass
class TorchReference(Reference):
    """An oracle written in PyTorch."""

    fn: Callable[..., torch.Tensor]
    name: str = "torch"

    def availability(self) -> Availability:
        return Availability(True)

    def __call__(self, *inputs: torch.Tensor) -> torch.Tensor:
        return self.fn(*inputs)


@dataclass(frozen=True)
class LaunchSpec:
    """How to launch the kernel under test.

    grid and block are callables of the input shapes so the driver can size the
    launch per case rather than hardcoding one shape.
    """

    kernel: str
    grid: Callable[[Sequence[tuple[int, ...]]], tuple[int, int, int]]
    block: tuple[int, int, int] = (256, 1, 1)
    scalar_args: Callable[[Sequence[tuple[int, ...]]], list[int]] = lambda shapes: []
    n_outputs: int = 1
    out_shape: Callable[[Sequence[tuple[int, ...]]], tuple[int, ...]] | None = None


_DRIVER = r"""
// Generated by hipbridge.verify. Reads inputs from binary files, launches the
// kernel once, writes outputs back. Deliberately dumb: no timing, no streams.
#include <cstdio>
#include <cstdlib>
#include <vector>
%(header)s

%(kernel_source)s

static std::vector<float> read_bin(const char* path, size_t n) {
    std::vector<float> h(n);
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %%s\n", path); exit(2); }
    if (fread(h.data(), sizeof(float), n, f) != n) { fprintf(stderr, "short read\n"); exit(3); }
    fclose(f);
    return h;
}

static void write_bin(const char* path, const std::vector<float>& h) {
    FILE* f = fopen(path, "wb");
    if (!f) { fprintf(stderr, "cannot open %%s\n", path); exit(4); }
    fwrite(h.data(), sizeof(float), h.size(), f);
    fclose(f);
}

int main(int argc, char** argv) {
    // argv: prog n_in (path size)*n_in out_path out_size gx gy gz bx by bz scalars...
    int argi = 1;
    int n_in = atoi(argv[argi++]);
    std::vector<float*> d_in(n_in);
    for (int i = 0; i < n_in; ++i) {
        const char* path = argv[argi++];
        size_t n = (size_t)atoll(argv[argi++]);
        auto h = read_bin(path, n);
        %(malloc)s(&d_in[i], n * sizeof(float));
        %(memcpy)s(d_in[i], h.data(), n * sizeof(float), %(h2d)s);
    }
    const char* out_path = argv[argi++];
    size_t out_n = (size_t)atoll(argv[argi++]);
    float* d_out = nullptr;
    %(malloc)s(&d_out, out_n * sizeof(float));

    // Fill the output with a sentinel so a kernel that never stores is caught.
    std::vector<float> sentinel(out_n, -12345.0f);
    %(memcpy)s(d_out, sentinel.data(), out_n * sizeof(float), %(h2d)s);

    int gx = atoi(argv[argi++]), gy = atoi(argv[argi++]), gz = atoi(argv[argi++]);
    int bx = atoi(argv[argi++]), by = atoi(argv[argi++]), bz = atoi(argv[argi++]);
    std::vector<int> scalars;
    for (; argi < argc; ++argi) scalars.push_back(atoi(argv[argi]));

    %(launch)s

    %(sync)s();
    auto err = %(last_error)s();
    if (err != %(success)s) {
        fprintf(stderr, "kernel error: %%s\n", %(error_string)s(err));
        return 5;
    }

    std::vector<float> h_out(out_n);
    %(memcpy)s(h_out.data(), d_out, out_n * sizeof(float), %(d2h)s);
    write_bin(out_path, h_out);
    return 0;
}
"""

_CUDA_TOKENS = {
    "header": "#include <cuda_runtime.h>",
    "malloc": "cudaMalloc",
    "memcpy": "cudaMemcpy",
    "h2d": "cudaMemcpyHostToDevice",
    "d2h": "cudaMemcpyDeviceToHost",
    "sync": "cudaDeviceSynchronize",
    "last_error": "cudaGetLastError",
    "success": "cudaSuccess",
    "error_string": "cudaGetErrorString",
}

_HIP_TOKENS = {
    "header": "#include <hip/hip_runtime.h>",
    "malloc": "hipMalloc",
    "memcpy": "hipMemcpy",
    "h2d": "hipMemcpyHostToDevice",
    "d2h": "hipMemcpyDeviceToHost",
    "sync": "hipDeviceSynchronize",
    "last_error": "hipGetLastError",
    "success": "hipSuccess",
    "error_string": "hipGetErrorString",
}

SENTINEL = -12345.0


@dataclass
class NativeReference(Reference):
    """Compile and run the original kernel source on a real device."""

    source: str
    launch: LaunchSpec
    toolchain: str = "nvcc"  # "nvcc" or "hipcc"
    extra_flags: list[str] = field(default_factory=list)
    name: str = "native"
    _built: Path | None = field(default=None, init=False, repr=False)

    def availability(self) -> Availability:
        exe = shutil.which(self.toolchain)
        if exe is None:
            return Availability(False, f"{self.toolchain} not on PATH")
        if self.toolchain == "nvcc" and not torch.cuda.is_available():
            return Availability(False, "nvcc present but no CUDA device visible")
        return Availability(True)

    def _render_driver(self) -> str:
        tokens = dict(_CUDA_TOKENS if self.toolchain == "nvcc" else _HIP_TOKENS)
        args = ", ".join(
            [f"d_in[{i}]" for i in range(64)][: self._n_inputs]
            + ["d_out"]
            + [f"scalars[{i}]" for i in range(self._n_scalars)]
        )
        if self.toolchain == "nvcc":
            call = f"{self.launch.kernel}<<<dim3(gx,gy,gz), dim3(bx,by,bz)>>>({args});"
        else:
            call = (
                f"hipLaunchKernelGGL({self.launch.kernel}, dim3(gx,gy,gz), "
                f"dim3(bx,by,bz), 0, 0, {args});"
            )
        tokens["launch"] = call
        tokens["kernel_source"] = self.source
        return _DRIVER % tokens

    def build(self, n_inputs: int, n_scalars: int) -> Path:
        self._n_inputs, self._n_scalars = n_inputs, n_scalars
        avail = self.availability()
        if not avail:
            raise RuntimeError(f"cannot build: {avail.reason}")

        tmp = Path(tempfile.mkdtemp(prefix="hipbridge_ref_"))
        ext = ".cu" if self.toolchain == "nvcc" else ".hip.cpp"
        src = tmp / f"driver{ext}"
        src.write_text(self._render_driver(), encoding="utf-8")
        exe = tmp / ("driver.exe" if Path(tempfile.gettempdir()).drive else "driver")

        cmd = [self.toolchain, str(src), "-o", str(exe), "-O2", *self.extra_flags]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"{self.toolchain} failed:\n{r.stderr[-2000:]}")
        self._built = exe
        return exe

    def __call__(self, *inputs: torch.Tensor) -> torch.Tensor:
        shapes = [tuple(t.shape) for t in inputs]
        scalars = self.launch.scalar_args(shapes)
        if self._built is None:
            self.build(len(inputs), len(scalars))
        assert self._built is not None

        tmp = self._built.parent
        argv: list[str] = [str(self._built), str(len(inputs))]
        for i, t in enumerate(inputs):
            p = tmp / f"in{i}.bin"
            flat = t.detach().cpu().contiguous().float().reshape(-1)
            p.write_bytes(struct.pack(f"<{flat.numel()}f", *flat.tolist()))
            argv += [str(p), str(flat.numel())]

        out_shape = self.launch.out_shape(shapes) if self.launch.out_shape else shapes[0]
        out_n = 1
        for d in out_shape:
            out_n *= d
        out_path = tmp / "out.bin"
        argv += [str(out_path), str(out_n)]
        argv += [str(x) for x in self.launch.grid(shapes)]
        argv += [str(x) for x in self.launch.block]
        argv += [str(x) for x in scalars]

        r = subprocess.run(argv, capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"reference run failed ({r.returncode}): {r.stderr[-1000:]}")

        raw = out_path.read_bytes()
        vals = struct.unpack(f"<{out_n}f", raw)
        return torch.tensor(vals, dtype=torch.float32).reshape(out_shape)


__all__ = [
    "SENTINEL",
    "Availability",
    "LaunchSpec",
    "NativeReference",
    "Reference",
    "TorchReference",
]
